# Generated by Django 5.1.3 on 2024-12-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=10)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('char_lock', models.CharField(max_length=100)),
                ('char_lock_limit', models.CharField(max_length=100)),
                ('punch_no', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='paraTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(blank=True, max_length=100)),
                ('channel_no', models.CharField(blank=True, max_length=10)),
                ('low_master', models.CharField(blank=True, max_length=100)),
                ('high_master', models.CharField(blank=True, max_length=100)),
                ('nominal', models.CharField(blank=True, max_length=100)),
                ('lsl', models.CharField(blank=True, max_length=100)),
                ('usl', models.CharField(blank=True, max_length=100)),
                ('ltl', models.CharField(blank=True, max_length=100)),
                ('utl', models.CharField(blank=True, max_length=100)),
                ('step_no', models.CharField(blank=True, max_length=10)),
                ('digits', models.CharField(blank=True, max_length=10)),
                ('id_od', models.CharField(blank=True, max_length=10)),
                ('parameter_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='app.parameter_settings')),
            ],
        ),
    ]
