# Generated by Django 5.1.3 on 2024-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paratabledata',
            name='auto_man',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paratabledata',
            name='timer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
