# Generated by Django 5.1.3 on 2024-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paratabledata_auto_man_paratabledata_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
            ],
        ),
    ]
