# Generated by Django 5.1.3 on 2024-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operator_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('a1', models.IntegerField()),
                ('b', models.FloatField()),
                ('b1', models.IntegerField()),
                ('e', models.CharField(max_length=10)),
                ('d', models.FloatField()),
                ('o1', models.FloatField()),
                ('parameter_name', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('mastering', models.CharField(max_length=10)),
                ('probe_number', models.IntegerField()),
            ],
        ),
    ]
