# Generated by Django 5.1.3 on 2024-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_port', models.CharField(max_length=255)),
                ('baud_rate', models.CharField(max_length=255)),
                ('parity', models.CharField(max_length=255)),
                ('stop_bit', models.CharField(max_length=255)),
                ('data_bit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=50)),
                ('shift_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
