# Generated by Django 5.1.3 on 2024-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comportsetting_data_shift_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comp_sr_no', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
                ('parameter_name', models.CharField(max_length=100)),
                ('lsl', models.FloatField()),
                ('usl', models.FloatField()),
                ('ltl', models.FloatField()),
                ('utl', models.FloatField()),
                ('nominal', models.FloatField()),
                ('output', models.FloatField()),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('tir_value', models.FloatField()),
                ('overall_status', models.CharField(max_length=100)),
            ],
        ),
    ]
