# Generated by Django 5.1.3 on 2024-12-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_measurementdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementData',
        ),
    ]
